# Generated by Django 5.1.1 on 2024-09-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(default='Dr. Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
