# Generated by Django 5.1.1 on 2024-09-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_patient_doctor_name_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(default='blank message', max_length=512),
        ),
    ]
